"""Snapshot provider voice for pending audio jobs"""

from alembic import op
import sqlalchemy as sa

revision = "27fc1722d51b"
down_revision = "9f4ca2f418ca"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audio_jobs", sa.Column("provider_voice", sa.String(length=40), server_default="Kore", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audio_jobs", "provider_voice")
    # ### end Alembic commands ###
